Repository kyma-project/eventing-auth-manager, pull requests merged in 2023-08, with the labels that each got.

#45 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, lgtm

#48 Fix flaky delete test
  controllers/eventingauth_controller_test.go
Labels: lgtm, size/XS

#47 Run unit tests with github action
  .github/workflows/unit-test.yml
Labels: area/ci, lgtm, size/M
