Repository kyma-project/eventing-auth-manager, pull requests merged in 2023-05, with the labels that each got.

#16 Implement Eventing Auth Kyma Controller
  README.md
  cmd/main.go
  config/crd/external/operator.kyma-project.io_kymas.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/operator_v1alpha1_eventingauth.yaml
  config/samples/operator_v1beta1_kyma.yaml
  controllers/eventingauth_controller_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
Labels: lgtm, size/XXL

#17 Add integration tests
  cmd/main.go
  controllers/client.go
  controllers/client_test.go
  controllers/eventingauth_controller.go
  controllers/eventingauth_controller_test.go
  controllers/kyma_controller.go
  controllers/stubs_test.go
  controllers/suite_test.go
  internal/ias/client.go
  internal/skr/client.go
  internal/skr/client_test.go
Labels: size/XL, lgtm

#22 Use exponential back-off instead of fixed retry
  cmd/main.go
  controllers/eventingauth_controller.go
  controllers/kyma_controller.go
  controllers/suite_test.go
Labels: lgtm, size/M
