Repository kyma-project/eventing-auth-manager, pull requests merged in 2023-04, with the labels that each got.

#4 add lint action
  .github/workflows/lint.yml
  CODEOWNERS
Labels: area/ci, lgtm, size/M

#3 Init manager
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  PROJECT
  README.md
  api/v1alpha1/eventingauth_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_eventingauths.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_eventingauths.yaml
  config/crd/patches/webhook_in_eventingauths.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/eventingauth_editor_role.yaml
  config/rbac/eventingauth_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/kustomization.yaml
  config/samples/operator_v1alpha1_eventingauth.yaml
  controllers/eventingauth_controller.go
  controllers/eventingauth_controller_test.go
  controllers/status.go
  controllers/suite_test.go
  docs/OWNERS
  docs/README.md
  go.mod
  go.sum
  hack/boilerplate.go.txt
  internal/ias/client.go
  internal/ias/internal/api/SCI_Application_Directory.yaml
  internal/ias/internal/api/ias.gen.go
  internal/ias/types.go
  main.go
Labels: area/documentation, lgtm, size/XXL

#5 Application creation resilience
  .mockery.yaml
  Dockerfile
  Makefile
  README.md
  cmd/main.go
  controllers/eventingauth_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  internal/ias/client.go
  internal/ias/client_test.go
  internal/ias/internal/mocks/client_with_responses_interface.go
Labels: lgtm, size/XXL

#6 Implement Deleting EventingAuth
  cmd/main.go
  controllers/eventingauth_controller.go
Labels: lgtm, size/M

#8 Implement Status Handling
  api/v1alpha1/eventingauth_types.go
  api/v1alpha1/status.go
  api/v1alpha1/status_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_eventingauths.yaml
  controllers/eventingauth_controller.go
  controllers/eventingauth_controller_test.go
  controllers/status.go
  controllers/suite_test.go
  internal/ias/client.go
  internal/ias/client_test.go
  internal/ias/types.go
Labels: size/XL, lgtm

#7 Create secret on target cluster
  cmd/main.go
  controllers/client.go
  controllers/client_test.go
  controllers/eventingauth_controller.go
  controllers/eventingauth_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  internal/ias/client.go
Labels: size/XL, lgtm

#9 Read token endpoint from well-known configuration
  controllers/eventingauth_controller_test.go
  controllers/suite_test.go
  internal/ias/client.go
  internal/ias/client_test.go
  internal/ias/internal/oidc/mocks/client.go
  internal/ias/internal/oidc/oidc-client.go
  internal/ias/internal/oidc/oidc-client_test.go
  internal/ias/types.go
Labels: size/L, lgtm

#11 Read ias secret
  .github/workflows/lint.yml
  Dockerfile
  cmd/main.go
  controllers/eventingauth_controller.go
  controllers/suite_test.go
  internal/ias/client.go
  internal/ias/ias_config.go
  internal/ias/ias_config_test.go
  internal/ias/internal/mocks/client_mock.go
Labels: size/L, area/ci, lgtm

#12 Fix reading kubeconfig secret
  config/rbac/role.yaml
  controllers/client.go
  controllers/eventingauth_controller.go
  controllers/suite_test.go
Labels: size/S, lgtm

#10 Documentation & Small Fixes
  Makefile
  README.md
  api/v1alpha1/eventingauth_types.go
  api/v1alpha1/status_test.go
  config/crd/bases/operator.kyma-project.io_eventingauths.yaml
  controllers/eventingauth_controller.go
  controllers/eventingauth_controller_test.go
  doc/controller-flow.svg
  doc/overview.svg
  internal/ias/client.go
  internal/ias/client_test.go
  internal/ias/internal/api/mocks/client_with_responses_interface.go
Labels: size/L, lgtm
