Repository kyma-project/eventing-auth-manager, pull requests merged in 2024-04, with the labels that each got.

#155 chore: added release pipeline
  .github/workflows/create-release.yml
  hack/scripts/await_pr_merge.sh
  hack/scripts/check_artifacts_existence.sh
  hack/scripts/check_publish_release_prerequisites.sh
  hack/scripts/check_release_tag.sh
  hack/scripts/create_draft_release.sh
  hack/scripts/create_scan_config.sh
  hack/scripts/create_sec_scanner_bump_pr.sh
  hack/scripts/publish_release.sh
  hack/scripts/releaselabelvalidator/release_label_validator.py
  hack/scripts/releaselabelvalidator/requirements.txt
Labels: size/XL, area/ci, lgtm, cla: yes

#157 fix: updated unit and integration tests in release pipeline
  .github/workflows/create-release.yml
Labels: area/ci, lgtm, size/M, cla: yes

#161 chore: update go version to 1.22.2
  Dockerfile
  go.mod
Labels: lgtm, size/XS, cla: yes

#162 chore: refactored go version in workflows
  .github/workflows/create-release.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint.yml
  .github/workflows/unit-test.yml
  Makefile
Labels: area/ci, size/S, lgtm, cla: yes

#164 fix: updates CR status when application secret already exists on cluster
  controllers/eventingauth_controller.go
  controllers/eventingauth_controller_test.go
Labels: lgtm, size/M, cla: yes

#160 chore: enabled validate labels step in create release workflow
  .github/release.yml
  .github/workflows/create-release.yml
Labels: area/ci, lgtm, size/M, cla: yes
