Repository kyma-project/eventing-auth-manager, pull requests merged in 2024-03, with the labels that each got.

#137 feat: reconcile Kymas only on CREATE
  cmd/main.go
  controllers/kyma_controller.go
Labels: lgtm, size/M, cla: yes

#140 chore: add slack notification on failure for integration test
  .github/workflows/integration-test.yml
  controllers/suite_test.go
Labels: area/ci, size/S, lgtm, cla: yes

#141 chore: bump kubernetes version for test
  Makefile
Labels: lgtm, size/XS, cla: yes

#142 chore: add stale action
  .github/workflows/lint.yml
  .github/workflows/stale.yml
  .gitignore
  .golangci.yaml
  Makefile
  cmd/main.go
  controllers/eventingauth_controller.go
  controllers/eventingauth_controller_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller_test.go
  controllers/stubs_test.go
  controllers/suite_test.go
  internal/ias/client.go
  internal/ias/client_test.go
  internal/ias/ias_config_test.go
  internal/ias/internal/oidc/oidc-client_test.go
  internal/skr/client.go
Labels: size/L, area/ci, lgtm, cla: yes

#144 fix: change k8s version in test
  .github/workflows/slack-failure-message.json
  Makefile
Labels: area/ci, lgtm, size/XS, cla: yes

#134 chore: introduce make target for external CRD generation
  .github/workflows/integration-test.yml
  .github/workflows/unit-test.yml
  Makefile
  config/crd/external/operator.kyma-project.io_kymas.yaml
  config/crd/external/operator.kyma-project.io_manifests.yaml
  config/crd/external/operator.kyma-project.io_moduletemplates.yaml
  config/crd/external/operator.kyma-project.io_watchers.yaml
  go.mod
  go.sum
  scripts/run-integration-test.sh
Labels: area/ci, lgtm, size/XXL, cla: yes

#145 chore: bump sec-scanner-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#148 fix: dont delete system namespaces after test
  controllers/suite_test.go
Labels: lgtm, size/XS, cla: yes

#90 Delete rbac-proxy resources as it cause security issues
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, area/eventing, size/M, cla: yes

#129 chore: Bump Go version in mod file
  go.mod
Labels: lgtm, size/XS, cla: yes

#143 feat: configurable global_account in ias application
  cmd/main.go
  controllers/eventingauth_controller.go
  controllers/stubs_test.go
  controllers/suite_test.go
  internal/ias/client.go
  internal/ias/client_test.go
Labels: lgtm, size/M, cla: yes
