Repository kyma-project/eventing-auth-manager, pull requests merged in 2024-09, with the labels that each got.

#211 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: lgtm, size/XS, cla: yes

#212 docs: add mandatory sections to readme
  README.md
Labels: size/S, lgtm, cla: yes

#217 chore: added github action based build jobs
  .github/workflows/pull-build-image.yaml
  .github/workflows/push-build-image.yaml
  .github/workflows/tag-build-image.yaml
Labels: size/L, area/ci, lgtm, cla: yes

#218 fix: changed Dockerfile working directory
  .github/workflows/pull-build-image.yaml
  Dockerfile
Labels: area/ci, size/S, lgtm, cla: yes

#220 chore: update token used in release pipeline
  .github/workflows/create-release.yml
Labels: area/ci, lgtm, size/XS, cla: yes, kind/enhancement
