Repository kyma-project/eventing-auth-manager, pull requests merged in 2024-02, with the labels that each got.

#114 Fix lint issues
  .gitignore
  Makefile
  api/v1alpha1/eventingauth_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/status_test.go
  cmd/main.go
  controllers/eventingauth_controller.go
  controllers/eventingauth_controller_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller_test.go
  controllers/stubs_test.go
  controllers/suite_test.go
  internal/ias/client.go
  internal/ias/client_test.go
  internal/ias/ias_config.go
  internal/ias/internal/oidc/oidc-client_test.go
Labels: size/L, lgtm, cla: yes

#115 Fix lint issues by importas linter
  api/v1alpha1/eventingauth_types.go
  api/v1alpha1/status.go
  api/v1alpha1/status_test.go
  cmd/main.go
  controllers/eventingauth_controller.go
  controllers/eventingauth_controller_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller_test.go
  controllers/stubs_test.go
  controllers/suite_test.go
  internal/ias/client.go
  internal/ias/client_test.go
  internal/ias/ias_config.go
  internal/ias/ias_config_test.go
  internal/ias/internal/mocks/client_mock.go
  internal/ias/types.go
  internal/skr/client.go
  internal/skr/client_test.go
Labels: size/XL, lgtm, cla: yes

#116 Fix lint issues
  api/v1alpha1/eventingauth_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/status.go
  api/v1alpha1/status_test.go
  cmd/main.go
  cmd/main_test.go
  controllers/eventingauth_controller.go
  controllers/eventingauth_controller_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller_test.go
  controllers/stubs_test.go
  controllers/suite_test.go
  internal/ias/client.go
  internal/ias/client_test.go
  internal/ias/ias_config.go
  internal/ias/ias_config_test.go
  internal/ias/internal/api/SCI_Application_Directory.yaml
  internal/ias/internal/api/ias.gen.go
  internal/ias/internal/oidc/oidc-client.go
  internal/ias/internal/oidc/oidc-client_test.go
  internal/ias/types.go
  internal/skr/client.go
  internal/skr/client_test.go
Labels: size/XL, lgtm, cla: yes

#117 Update code linter job
  .github/workflows/lint.yml
  controllers/eventingauth_controller.go
Labels: area/ci, lgtm, size/M, cla: yes

#119 feat: add rules for PRs
  .github/dependabot.yml
  .github/workflows/lint-conventional-prs.yml
Labels: area/ci, lgtm, size/M, cla: yes

#127 chore: change dependabot config to weekly schedule
  .github/dependabot.yml
Labels: area/ci, size/S, lgtm, cla: yes

#130 Fix schedule of DependaBot
  .github/dependabot.yml
Labels: area/ci, lgtm, size/XS, cla: yes

#131 chore: introduce IAS integration test
  .github/workflows/integration-test.yml
  Makefile
  config/crd/bases/operator.kyma-project.io_eventingauths.yaml
  hack/provision-k3d.sh
Labels: area/ci, lgtm, size/M, cla: yes

#136 fix: update ownerrefs on EA-CR to latest kyma api-version
  controllers/eventingauth_controller_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller_test.go
  controllers/suite_test.go
Labels: size/L, lgtm, cla: yes
